# check the panic function
fail godebugtester run main.go
contains stdout "recv: => panic(\"!\")"
#contains stderr "panic: !"
fail contains stdout "_ := 1"

-- main.go --
package main
func main() {
	panic("!")
	_=1 // not reachable
}

